export const envList = {
  PUBLIC_BUILDER_API_KEY: "PUBLIC_BUILDER_API_KEY",
  MAIN_URL: "MAIN_URL",
  EP_MAIN: "EP_MAIN",
  EP_ACTIVITY: "EP_ACTIVITY",
  EP_CHANNEL: "EP_CHANNEL",
  EP_COMMENT: "EP_COMMENT",
  EP_GA: "EP_GA",
  EP_PLAYLIST: "EP_PLAYLIST",
  EP_S3: "EP_S3",
  EP_THUMBNAIL: "EP_THUMBNAIL",
  EP_USER: "EP_USER",
  EP_VIDEO: "EP_VIDEO",
};
